# Generated by Django 2.2.5 on 2019-11-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_chat', models.BooleanField(default=False, verbose_name='групповой или нет')),
                ('topic', models.CharField(max_length=60, verbose_name='название')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_messages', models.IntegerField(default=0, verbose_name='количество непрочитанных сообщений в конкретном чате')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='chats.Chat', verbose_name='чат')),
            ],
            options={
                'verbose_name': 'участник чата',
                'verbose_name_plural': 'участники чата',
            },
        ),
    ]
