# Generated by Django 2.2.5 on 2019-11-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20191127_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='avatar',
        ),
    ]
