# Generated by Django 2.2.5 on 2019-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_info', '0002_auto_20191106_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type_of_attachment',
            field=models.CharField(max_length=20, verbose_name='формат'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(max_length=100, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False, verbose_name='групповой или нет'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=5000, verbose_name='текст последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=60, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default='1970-01-01 12:00:00', verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=5000, verbose_name='текст сообщения'),
        ),
    ]
