# Generated by Django 2.2.5 on 2019-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_attachment', models.CharField(max_length=20, verbose_name='формат вложения')),
                ('url', models.CharField(max_length=200, verbose_name='url вложения')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
            },
        ),
    ]
