# Generated by Django 2.2.5 on 2019-11-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachment_chat'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='message.Message', verbose_name='сообщение, к которому прикреплено вложение'),
        ),
    ]
