# Generated by Django 2.2.5 on 2019-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
