# Generated by Django 2.2.5 on 2019-11-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20191105_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
